# **NOTE:** Use File > Save a copy in Drive to make a copy before doing anything else

# Project 7: Student Habits vs Academic Performance Analysis

#### Overview

This project analyzes the relationship between student lifestyle habits and academic performance using a comprehensive dataset from Kaggle. The dataset contains information about 1,000 students and includes 16 variables covering various aspects of student life, including study habits, social media usage, sleep patterns, diet quality, exercise frequency, and academic outcomes.

The analysis focuses on understanding how different study patterns correlate with exam performance.The project demonstrates fundamental data analysis skills including data cleaning, statistical calculations, and comparative analysis using Python and pandas.

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
# Update file_path to point to the specific file within the dataset
file_path = "student_habits_performance.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "jayaantanaath/student-habits-vs-academic-performance",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipython-input-159/3453289196.py:11: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/jayaantanaath/student-habits-vs-academic-performance?dataset_version_number=1&file_name=student_habits_performance.csv...

100%|██████████| 71.9k/71.9k [00:00<00:00, 24.8MB/s]

First 5 records:   student_id  age  gender  study_hours_per_day  social_media_hours  \
0      S1000   23  Female                  0.0                 1.2
1      S1001   20  Female                  6.9                 2.8
2      S1002   21    Male                  1.4                 3.1
3      S1003   23  Female                  1.0                 3.9
4      S1004   19  Female                  5.0                 4.4

   netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0            1.1            No                   85.0          8.0
1            2.3            No                   97.3          4.6
2            1.3            No                   94.8          8.0
3            1.0            No                   71.0          9.2
4            0.5            No                   90.9          4.9

  diet_quality  exercise_frequency parental_education_level internet_quality  \
0         Fair                   6                   Master          Average
1         Good                   6              High School          Average
2         Poor                   1              High School             Poor
3         Poor                   4                   Master             Good
4         Fair                   3                   Master             Good

   mental_health_rating extracurricular_participation  exam_score
0                     8                           Yes        56.2
1                     8                            No       100.0
2                     1                            No        34.3
3                     1                           Yes        26.8
4                     1                            No        66.4

In [ ]:
one_col = df['age']

In [ ]:
type(one_col)

pandas.core.series.Series

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   object
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   object
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   object
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   object
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    object
 12  internet_quality               1000 non-null   object
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   object
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), object(7)
memory usage: 125.1+ KB

In [ ]:
df.shape

(1000, 16)

In [ ]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='object')

### clean the data

In [ ]:
df.isnull().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

This checks how many missing (NaN) values are in each column of the DataFrame. Based on the output:

All columns have 0 missing values except for parental_education_level, which has 91 missing values.

The dataset is mostly clean, but you do need to clean or handle the missing data in the parental_education_level column.

#### Fill with a default or common value

#### drop rows with missing values

In [ ]:
df.dropna(subset=['parental_education_level'], inplace=True)

In [ ]:
# checking the data again
df.isnull().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [ ]:
 # space

In [ ]:
# question one

avg_study_hours = df['study_hours_per_day'].mean()
print(f"The average study hours per day for all students is: {avg_study_hours:.2f}")

The average study hours per day for all students is: 3.54

In [ ]:
# question two

most_study_student = df.loc[df['study_hours_per_day'].idxmax()]

print(f"The student who studies the most is {most_study_student['student_id']} with {most_study_student['study_hours_per_day']} hours per day.")
display(most_study_student.to_frame().T)

The student who studies the most is S1455 with 8.3 hours per day.

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
455,S1455,19,Male,8.3,3.3,2.6,Yes,86.6,6.5,Fair,5,High School,Average,9,No,100.0

In [ ]:
# question three

students_more_than_6 = df[df['study_hours_per_day'] > 6]
count_more_than_6 = len(students_more_than_6)
print(f"The number of students who study more than 6 hours per day is: {count_more_than_6}")

The number of students who study more than 6 hours per day is: 40

In [ ]:
# question four

percentage_more_than_6 = (len(df[df['study_hours_per_day'] > 6]) / len(df)) * 100
print(f"The percentage of students who study more than 6 hours per day is: {percentage_more_than_6:.2f}%")

The percentage of students who study more than 6 hours per day is: 4.40%

In [ ]:
# question five

percentage_less_than_2 = (df['study_hours_per_day'] < 2).mean() * 100
print(f"The percentage of students who study less than 2 hours per day is: {percentage_less_than_2:.2f}%")

The percentage of students who study less than 2 hours per day is: 13.53%

In [ ]:
# question six

more_than_5 = df[df['study_hours_per_day'] > 5]['exam_score'].mean()
less_or_equal_5 = df[df['study_hours_per_day'] <= 5]['exam_score'].mean()

print(f"Average exam score for students studying > 5 hours: {more_than_5:.2f}")
print(f"Average exam score for students studying <= 5 hours: {less_or_equal_5:.2f}")

if more_than_5 > less_or_equal_5:
    print("\nYes, students who study more than 5 hours per day have a higher average exam score.")
else:
    print("\nNo, students who study more than 5 hours per day do not have a higher average exam score.")

Average exam score for students studying > 5 hours: 91.12
Average exam score for students studying <= 5 hours: 65.67

Yes, students who study more than 5 hours per day have a higher average exam score.

### Questions to Answer

Please find the answer for the following questoins.

1. Find the average study hours per day for all students. Please create a code cell below this to answer the question.(0.5 point)

2. Identify the student who studies MOST hours per day. Please create a code cell below to answer the question.(0.5 point)

3. Count how many students study more than 6 hours per day. Please create a code cell below this to answer the question.(0.5 point)

4. What is the percentage of students who study more than 6 hours per day. Please create a code cell below this to answer the question.(0.5 point)

5. Calculate what percentage of students study less than 2 hours per day. Please create a code cell below this to answer the question.(0.5 point)

6. Do students who study more than 5 hours per day have higher exam scores on average? Please create a code cell below to answer this question. (0.5 point)

7. Use "Explain code" for the code you produced for Question 6 and summarize in your own words to show that you understood the code Gemini produced. Please create a text cell below to answer this question. (0.5 point)

Its working as an else if statement that has to process its variables and their relationship in conjunction with what the code is asking it to do. It then compares the two numbers, the variables, and then displays/answers the code question.

8. The codes produced to answer the questions use "vectorization"? Please justify your answer with an example. Please create a text cell below to answer this question. (0.5 point)

For this project where there is wide data sets, numbers associated with multiple of differing values and tables. Vecorization in this context is to give us the actualized value in the context given